### ISSUE TITLE
[Bug] Search Box Gone (BetterDiscord?)

### ISSUE THREAD

**Issue by DracoClaw** [CreArts-Community/Friends-Grid#8] opened 2022-01-16 17:01 UTC
Discord added a search box for the friends list, but with this theme enabled the box disappears.

**Comment by CorellanStoma** [comment] 2022-01-16 18:06
hmm I've heard the problem from a few people, but I don't know what could be the problem, in my Powercord version everything works so far:
![image](https://user-images.githubusercontent.com/58918358/149672154-f75f666a-2d0c-4a94-8d97-3fc43006621f.png)

I also have no problems with GooseMod.

**Comment by cxmmunist** [comment] 2022-01-19 09:36
same, laptop here

**Comment by DracoClaw** [comment] 2022-01-19 14:08
IDK what changed, but now the searchbox works and is there. Only thing i can think of is PinDM got an update?

**Comment by CorellanStoma** [comment] 2022-01-20 00:37
The problem is really weird, I can't reproduce it either, the code is perfectly fine.

**Comment by cxmmunist** [comment] 2022-01-20 09:53
@DracoClaw still gone for me...hm.

**Comment by cxmmunist** [comment] 2022-01-21 14:05
> IDK what changed, but now the searchbox works and is there. Only thing i can think of is PinDM got an update?

oh btw, i dont use PinDM and its broken :(

**Comment by CorellanStoma** [comment] 2022-01-23 23:37
Well I'm not quite sure, but I think the problem with the grid and the search bar are somehow related.

It seems that some clients have different classes than others, despite having the same version.
![image](https://user-images.githubusercontent.com/58918358/150702758-eea31c31-4942-40c1-ba4c-002a9674d112.png)

**Comment by CorellanStoma** [comment] 2022-01-23 23:48
![image](https://user-images.githubusercontent.com/58918358/150703138-15c52366-633f-4e2e-968f-bf09e7cbfc8c.png)

**Comment by CorellanStoma** [comment] 2022-01-24 01:32
I published a new version, it should be fixed now:
https://github.com/CreArts-Community/Friends-Grid/releases/tag/v1.0.8

**Comment by cxmmunist** [comment] 2022-01-24 06:11
yup

**Closed** 2022-01-24 21:18 UTC
Labels: Bug
